export const coordinatorPermissions = [
  'user_get_by_id',
  'user_confirm',
  'event_list',
  'event_get_by_id',
  'generic_list',
  'participant_create',
  'participant_list',
  'activity_list',
  'activity_create',
  'activity_update_by_id',
  'activity_delete_by_id',
  'certificate_list',
  'certificate_create',
  'certificate_delete_by_id',
  'model_list',
  'model_create',
  'model_delete_by_id'
]
