FROM node:14-alpine

WORKDIR /usr/src/app

COPY package.json yarn.lock prettier.config.js tsconfig.json .eslintrc.js .eslintignore ./
COPY packages/shared ./packages/shared
COPY packages/backend/generic/package.json ./packages/backend/generic/

RUN yarn && yarn cache clean

COPY packages/backend/generic/ ./packages/backend/generic/
