FROM node:alpine

WORKDIR /usr/src/app

COPY package.json yarn.lock prettier.config.js tsconfig.json .eslintrc.js .eslintignore ./
COPY packages/shared ./packages/shared
COPY packages/backend/gateway/package.json ./packages/backend/gateway/

RUN yarn && yarn cache clean

COPY packages/backend/gateway/ ./packages/backend/gateway/
