FROM node:14-alpine

WORKDIR /usr/src/app

COPY package.json yarn.lock prettier.config.js tsconfig.json .eslintrc.js .eslintignore ./
COPY packages/shared ./packages/shared
COPY packages/frontend/web/package.json ./packages/frontend/web/

RUN yarn && yarn cache clean

COPY packages/frontend/web/ ./packages/frontend/web/
