FROM node:alpine

WORKDIR /usr/src/app

COPY package.json yarn.lock prettier.config.js tsconfig.json .eslintrc.js .eslintignore ./
COPY packages/shared ./packages/shared
COPY packages/backend/token/package.json ./packages/backend/token/

RUN yarn && yarn cache clean

COPY packages/backend/token/ ./packages/backend/token/
