FROM node:14-alpine

WORKDIR /usr/src/app

COPY package.json yarn.lock prettier.config.js tsconfig.json .eslintrc.js .eslintignore ./
COPY packages/shared ./packages/shared
COPY packages/backend/permission/package.json ./packages/backend/permission/

RUN yarn && yarn cache clean

COPY packages/backend/permission/ ./packages/backend/permission/
