import {
  FiAward,
  FiBriefcase,
  FiBook,
  FiBookOpen,
  FiCalendar,
  FiClipboard,
  FiCode,
  FiCompass,
  FiCpu,
  FiDatabase,
  FiEye,
  FiFilm,
  FiFlag,
  FiGlobe,
  FiHeart,
  FiHome,
  FiLayout,
  FiMessageCircle,
  FiMessageSquare,
  FiMic,
  FiMonitor,
  FiMusic,
  FiPenTool,
  FiPackage,
  FiRefreshCw,
  FiStar,
  FiTag,
  FiTarget,
  FiTerminal,
  FiTool,
  FiUserCheck,
  FiUsers,
  FiZap
} from 'react-icons/fi'

export const ICON_MAP: Record<string, React.ComponentType<{ size?: number }>> = {
  FiAward,
  FiBriefcase,
  FiBook,
  FiBookOpen,
  FiCalendar,
  FiClipboard,
  FiCode,
  FiCompass,
  FiCpu,
  FiDatabase,
  FiEye,
  FiFilm,
  FiFlag,
  FiGlobe,
  FiHeart,
  FiHome,
  FiLayout,
  FiMessageCircle,
  FiMessageSquare,
  FiMic,
  FiMonitor,
  FiMusic,
  FiPenTool,
  FiPackage,
  FiRefreshCw,
  FiStar,
  FiTag,
  FiTarget,
  FiTerminal,
  FiTool,
  FiUserCheck,
  FiUsers,
  FiZap
}

export const ICON_OPTIONS = Object.keys(ICON_MAP)

export function getIcon(name?: string): React.ComponentType<{ size?: number }> {
  return (name && ICON_MAP[name]) || FiTag
}
