name: Deploy Storage Service

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/backend/storage/**'

  workflow_dispatch:
    inputs:
      force_deploy:
        description: "Forçar deploy mesmo sem mudanças"
        required: false
        default: "false"

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.force_deploy == 'true')

    steps:
      - name: Trigger Coolify Deploy
        run: |
          curl -X POST \
            --fail --fail-with-body --show-error \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}" \
            "${{ secrets.COOLIFY_STORAGE_WEBHOOK }}"
